# Generated by Django 4.1.2 on 2022-10-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_is_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='image',
            new_name='avatar',
        ),
    ]
